version: '3.4'

networks:
  dev:
    driver: bridge

services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - ${PWD}/work/jenkins:/var/jenkins_home
    ports:
      - 8000:8080
    networks:
      - dev
  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - "${PWD}/init/selenoid/config:/etc/selenoid"
      - "${PWD}/work/selenoid/video:/opt/selenoid/video"
      - "${PWD}/work/selenoid/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=work/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
    network_mode: bridge
  jira:
    image: atlassian/jira-software
    volumes:
    - "${PWD}/work/jira:/var/atlassian/application-data/jira"
    ports:
      - "9999:8080"
    networks:
      - dev